"""Render health-check results as a Markdown report.

Same table, same columns, same worst-first order as ``render_html`` -- but
plain Markdown, so it drops straight into a GitHub/GitLab issue, a PR
description, a wiki page, or a team status doc, where those platforms render
the table natively. Like ``--html`` (and unlike ``--dashboard``) it's a
static artifact with nothing to break: safe to diff, grep, or paste.

``_primary_owner`` / ``_flag`` / ``_flag_tri`` are duplicated from the other
renderer modules on purpose -- see ``render_dashboard`` and the project
``CLAUDE.md`` for why there's no shared utils module here.
"""

from __future__ import annotations

from collections import Counter
from datetime import datetime

from repo_healthcheck.health import RepoHealth

__all__ = ["render"]


def _primary_owner(results: list[RepoHealth]) -> str:
    """The most-represented owner -- see render_dashboard._primary_owner
    for why only non-primary-owner repos keep their owner/ prefix here.
    """
    counts = Counter(h.repo.owner for h in results)
    return counts.most_common(1)[0][0] if counts else ""


def _flag(ok: bool) -> str:
    return "✓" if ok else "✗"


def _flag_tri(ok: bool | None) -> str:
    if ok is None:
        return "?"
    return _flag(ok)


def _informational_flag(ok: bool) -> str:
    # Shown but never counted as an issue (e.g. src/ layout, see health.py).
    return "✓" if ok else "—"


def _cell(text: str) -> str:
    r"""Make free text safe inside a Markdown table cell: escape the pipe that
    would otherwise start a new column, and flatten any newlines.
    """
    return text.replace("|", r"\|").replace("\n", " ").strip()


_COLUMNS = (
    ("repo", "---"),
    ("readme", ":-:"),
    ("claude.md", ":-:"),
    ("protected", ":-:"),
    ("license", ":-:"),
    ("contributors", "-:"),
    ("forks", "-:"),
    ("description", ":-:"),
    ("topics", ":-:"),
    ("src/", ":-:"),
    ("pushed", "---"),
    ("issues", "---"),
)


def render(results: list[RepoHealth]) -> str:
    """Return a complete Markdown document as a string."""
    unhealthy = sum(1 for h in results if not h.is_healthy)
    generated = datetime.now().strftime("%Y-%m-%d %H:%M")
    primary_owner = _primary_owner(results)

    lines = [
        "# repo-healthcheck — repo health report",
        "",
        f"{len(results)} repos, {unhealthy} with at least one issue. "
        f"Generated {generated}.",
    ]
    if primary_owner:
        lines += [
            "",
            f"Repos owned by **{_cell(primary_owner)}** are shown without the "
            f"owner prefix.",
        ]
    lines += [
        "",
        "| " + " | ".join(name for name, _ in _COLUMNS) + " |",
        "| " + " | ".join(align for _, align in _COLUMNS) + " |",
    ]

    for h in results:
        r = h.repo
        display_name = r.name if r.owner == primary_owner else r.full_name
        label = _cell(display_name)
        if r.platform != "github":
            label += f" ({r.platform})"
        if r.archived:
            label += " (archived)"
        # link title carries the full owner/name even when the label is short,
        # matching render_html's title attribute
        repo_cell = f'[{label}]({r.url} "{_cell(r.full_name)}")' if r.url else label

        contributors = "?" if r.contributors is None else str(r.contributors)
        issue_cell = "ok" if h.is_healthy else _cell("; ".join(h.issues))

        lines.append(
            "| "
            + " | ".join(
                (
                    repo_cell,
                    _flag(r.has_readme),
                    _flag(r.has_claude_md),
                    _flag_tri(r.branch_protected),
                    _flag(bool(r.license)),
                    contributors,
                    str(r.forks),
                    _flag(bool(r.description)),
                    _flag(bool(r.topics)),
                    _informational_flag(r.has_src_layout),
                    _cell(r.pushed),
                    issue_cell,
                )
            )
            + " |"
        )

    lines += [
        "",
        "`src/` is informational only — never counted as an issue.",
        "",
        "_Generated by [repo-healthcheck](https://github.com/ubeast/repo-healthcheck)._",
        "",
    ]
    return "\n".join(lines)
